# Generated by Django 4.2.11 on 2024-07-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_library_w_career_category_level_1', to='api.imagelibrary')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('career_category_level1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_category_level_1_w_career_category_level_2', to='api.careercategorylevel1')),
            ],
        ),
    ]
