# Generated by Django 4.2.11 on 2024-07-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_careercategorylevel2_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careercategorylevel1',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careercategorylevel2',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
