# Generated by Django 4.2.11 on 2024-07-30 01:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_careercategorylevel1_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
