# Generated by Django 4.2.11 on 2024-07-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_companyprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerprofile',
            name='name',
        ),
    ]
