# Generated by Django 4.2.11 on 2024-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_careerprofile_is_teacher_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprofile',
            name='count_change_password',
            field=models.IntegerField(default=0),
        ),
    ]
