# Generated by Django 4.2.11 on 2024-07-31 03:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_careerprofile_count_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('time_take_place', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverseasAreas',
            fields=[
                ('oversea_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QAPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('like', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_w_qa_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=255)),
                ('tuition', models.CharField(max_length=255)),
                ('graduation_exam_score', models.CharField(max_length=255)),
                ('number_of_student', models.IntegerField()),
                ('infrastructure', models.CharField(max_length=255)),
                ('employment_rate_after_graduation', models.CharField(max_length=255)),
                ('instructor_educational_background', models.CharField(max_length=255)),
                ('career_category_level2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_category_level2_w_school_post', to='api.careercategorylevel2')),
                ('local_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_areas_w_school_post', to='api.localareas')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_library_w_school_post', to='api.imagelibrary')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('like', models.IntegerField(default=0)),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_w_reply', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_w_reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('work_location_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('local_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_areas_w_recruitment_post', to='api.localareas')),
                ('oversea_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overseas_areas_w_recruitment_post', to='api.overseasareas')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_w_recruitment_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAPost_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
                ('qa_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_post_w_qa_post_notifications', to='api.qapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_w_qa_post_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAPost_Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('qa_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_post_w_qa_post_follower', to='api.qapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_w_qa_post_follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='overseasareas',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_w_overseas_areas', to='api.region'),
        ),
        migrations.AddField(
            model_name='localareas',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_w_local_areas', to='api.region'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('like', models.IntegerField(default=0)),
                ('qa_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_post_w_comment', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_w_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategoryLevel2_RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_category_level2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_category_level2_w_career_category_level2_recruitment_post', to='api.careercategorylevel2')),
                ('recruitment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_post_w_career_category_level2_recruitment_post', to='api.recruitmentpost')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategory2_QAPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_category_level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_category_level2_w_career_category_level_2_qa_post', to='api.careercategorylevel2')),
                ('qa_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_post_w_career_category_level_2_blog_post', to='api.qapost')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategory2_BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_w_career_category_level_2_blog_post', to='api.blogpost')),
                ('career_category_level2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_category_level2_w_career_category_level_2_blog_post', to='api.careercategorylevel2')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='local_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_areas_w_blog_post', to='api.localareas'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='oversea_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overseas_areas_w_blog_post', to='api.overseasareas'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_library_w_blog_post', to='api.imagelibrary'),
        ),
        migrations.CreateModel(
            name='ApplicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_library_w_application_profile', to='api.documentlibrary')),
                ('recruitment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_post_w_application_profile', to='api.recruitmentpost')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_w_application_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
