# Generated by Django 4.2.11 on 2024-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blogpost_localareas_overseasareas_qapost_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_college_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_support_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='is_teacher_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
